### ISSUE TITLE
Wrong Arxiv link

### ISSUE THREAD

**Issue by pd162** [SkalskiP/top-cvpr-2023-papers#9]
Thanks for your contribution! I found a wrong link exists of the paper "_Open-Vocabulary Semantic Segmentation with Mask-adapted CLIP_". The correct link is here[https://arxiv.org/abs/2210.04150]. Hope to correct it as soon as possible!

**Comment by SkalskiP** [comment]
Hi, @pd162 👋🏻! It looks like we just fixed those incorrect links. I'm closing the issue, but if you find any more problems feel free to reopen it.
